# Generated by Django 5.1.4 on 2025-01-09 00:52

import apis.api_carpeta.funciones_custom.guardar_carpeta
import apis.api_carpeta.funciones_custom.validar_pdf
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_datoscarpeta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloCarpeta',
            fields=[
                ('codigo_interno', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('nro_dim', models.CharField(max_length=20, unique=True)),
                ('fecha_apertura', models.DateField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('aduana_despacho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_datoscarpeta.modeloaduanadespacho')),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_datoscarpeta.modelocanalapertura')),
                ('clasificacion_carpeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_datoscarpeta.modeloclasificacioncarpeta')),
                ('importador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_datoscarpeta.modeloimportador')),
                ('mercaderia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_datoscarpeta.modelomercaderia')),
                ('modalidad_despacho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_datoscarpeta.modelomodalidaddespacho')),
            ],
            options={
                'verbose_name': 'Carpeta',
                'verbose_name_plural': 'Carpetas',
                'ordering': ['fecha_apertura'],
            },
        ),
        migrations.CreateModel(
            name='ModeloPersonalCarpeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_asignado', models.CharField(choices=[('tramitador', 'tramitador'), ('liquidador', 'liquidador')], max_length=10, validators=[django.core.validators.RegexValidator(message='rol no permitido', regex='^(tramitador|liquidador)$')])),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('carpeta_asignada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_carpeta.modelocarpeta')),
                ('personal_asignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_datoscarpeta.modelopersonalagencia')),
            ],
            options={
                'verbose_name': 'Asignado a Carpeta',
                'verbose_name_plural': 'Personal Carpeta',
                'ordering': ['creado'],
            },
        ),
        migrations.CreateModel(
            name='ModeloTipoArchivoCarpeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('carpeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipoarchivo_carpeta_set', to='api_carpeta.modelocarpeta')),
                ('tipo_archivo', models.ManyToManyField(to='api_datoscarpeta.modelotipoarchivo')),
            ],
            options={
                'verbose_name': 'Asignacion Archivo Carpeta',
                'verbose_name_plural': 'Asignacion Archivos Carpetas',
                'ordering': ['creado'],
            },
        ),
        migrations.CreateModel(
            name='ModeloDocumentoSoporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_referencia', models.CharField(max_length=75)),
                ('respaldo', models.FileField(blank=True, upload_to=apis.api_carpeta.funciones_custom.guardar_carpeta.get_upload_to, validators=[apis.api_carpeta.funciones_custom.validar_pdf.validate_pdf])),
                ('estado_archivo', models.CharField(choices=[('original', 'original'), ('copia', 'copia'), ('fotocopia', 'fotocopia'), ('fax', 'fax')], max_length=10, validators=[django.core.validators.RegexValidator(message='Estado del archivo inválido', regex='^(original|copia|fotocopia)$')])),
                ('estado_respaldo', models.CharField(choices=[('adjunto', 'adjunto'), ('no adjunto', 'no adjunto')], default='no adjunto', max_length=10, validators=[django.core.validators.RegexValidator(message='Estado del respaldo inválido', regex='^(adjunto|no adjunto)$')])),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('carpeta_tipoarchivo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api_carpeta.modelotipoarchivocarpeta')),
            ],
            options={
                'verbose_name': 'Documento Respaldo',
                'verbose_name_plural': 'Documentos Respaldo',
                'ordering': ['creado'],
            },
        ),
        migrations.AddIndex(
            model_name='modelocarpeta',
            index=models.Index(fields=['fecha_apertura'], name='api_carpeta_fecha_a_59343f_idx'),
        ),
        migrations.AddIndex(
            model_name='modelopersonalcarpeta',
            index=models.Index(fields=['creado'], name='api_carpeta_creado_0b83bd_idx'),
        ),
        migrations.AddConstraint(
            model_name='modelopersonalcarpeta',
            constraint=models.UniqueConstraint(fields=('personal_asignado', 'carpeta_asignada', 'rol_asignado'), name='unique_personal_carpeta_rol_asignado'),
        ),
        migrations.AddIndex(
            model_name='modelotipoarchivocarpeta',
            index=models.Index(fields=['creado'], name='api_carpeta_creado_a74a08_idx'),
        ),
        migrations.AddIndex(
            model_name='modelodocumentosoporte',
            index=models.Index(fields=['creado'], name='api_carpeta_creado_b0f915_idx'),
        ),
        migrations.AddConstraint(
            model_name='modelodocumentosoporte',
            constraint=models.UniqueConstraint(fields=('codigo_referencia', 'carpeta_tipoarchivo'), name='unique_codigo_referencia_carpeta_tipoarchivo'),
        ),
    ]
