# Generated by Django 5.1.4 on 2025-01-09 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_carpeta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelodocumentosoporte',
            name='carpeta_tipoarchivo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documento_soporte', to='api_carpeta.modelotipoarchivocarpeta'),
        ),
    ]
