# Generated by Django 5.1.4 on 2025-01-27 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_carpeta', '0003_alter_modelocarpeta_options_and_more'),
        ('api_datoscarpeta', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelocarpeta',
            options={'ordering': ['-codigo_interno'], 'verbose_name': 'Carpeta', 'verbose_name_plural': 'Carpetas'},
        ),
        migrations.RemoveIndex(
            model_name='modelocarpeta',
            name='api_carpeta_codigo__7da7c4_idx',
        ),
        migrations.AddIndex(
            model_name='modelocarpeta',
            index=models.Index(fields=['-codigo_interno'], name='api_carpeta_codigo__6c3345_idx'),
        ),
    ]
